language: node_js
node_js:
  - "0.10"
before_install:
  - npm install -g grunt-cli
  - sudo apt-get install -qq ruby
  - gem install sass
install:
  - npm install
script:
  - grunt travis-ci
notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#bricksframework"
    template:
      - "Results: %{repository_slug} (%{commit}) : %{message} %{build_number}"
      - "Build details: %{build_url} %{duration} %{branch}"